# Generated by Django 5.0.6 on 2024-08-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmwr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
                ('dias', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nivel', models.CharField(max_length=40)),
            ],
        ),
    ]
