# Generated by Django 5.0.6 on 2024-08-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmwr', '0002_clases_profesores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Alumnos',
        ),
    ]
