# Generated by Django 5.0.6 on 2024-08-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmwr', '0003_rename_clientes_alumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Clases',
            new_name='Clase',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
    ]
