# Generated by Django 5.0.6 on 2024-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmwr', '0004_rename_alumnos_alumno_rename_clases_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='dias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clase',
            name='nivel',
            field=models.CharField(max_length=50),
        ),
    ]
